# Generated by Django 3.2.12 on 2024-06-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('teacher_id', models.ImageField(upload_to='')),
                ('email', models.EmailField(max_length=254)),
                ('subject_specialization', models.CharField(max_length=25)),
                ('years_of_expperience', models.IntegerField()),
                ('biography', models.TextField()),
            ],
        ),
    ]
